#+TITLE: K-12 Research Explorations Github Syllabus
#+AUTHOR: Leilani Gilpin
#+MACRO: quarter Summer 2026

* Skill-Building and Independent Research Experiences in the AIEA Lab for K-12 students

There are two tracks:
1. [AIEA project track](auditor-onboarding/) this is for *new K-12
   students* that are interested in learning about the active projects
   in the AIEA Lab.  To be eligible to join the lab after summer as an
   *active member* (see below) you must complete the 10 onboarding
   tasks within the summer.
2. [Independent track](independent-research/) this is for *any K-12
   student* that is interested in learning more about research in the
   AIEA lab by proposed their own project.  
** Instructor Information
Leilani H. Gilpin (she/her), Assistant Professor of CSE Email:
lgilpin@ucsc.edu Office: E2 347B Office Hours: By appointment

I am excited about teaching intelligent systems to explain
themselves. I joined the faculty of UCSC in 2021 as an Assistant
Professor in Computer Science and Engineering. I previously developed
a new, short course on AI and global risks at MIT, and was a teaching
assistant for Large Scale Symbolic Systems. I typically teach AI (CSE
140, CSE 240) and responsible data science (CSE 246) and Machine
Learning (CSE 142, CSE 242).
** Experience Overview
The course is structured around a set of deliverables, meetings, and
status forms.  Students will work either individually or in small
teams of 2-4 persons to complete a set of deliverables over the
summer. The expected commitment is ~10 hours per week. Each task will
require a set of deliverables to be submitted via a weekly form (e.g.,
presentation, report, code, results).

The full grading guidelines are available
[here](https://www.notion.so/aiea/Grading-Guidelines-32fc03a14c2c8031a002d1e398eb8fca?source=copy_link).

Students interested in joining the AIEA lab as an active member must
complete all the tasks of their chosen project, regardless of the
number of points earned, as these tasks are the basics of the research
projects carried on by our lab. All the students who complete the 10
deliverables by the end of the summer (the **last day of instruction**)
will be invited to become an active lab member of the AIEA lab.

** Projects
The available projects for {{{quarter}}} are:
- Robustifying Autonomous Vehicles (AVs)
- NeuroSymbolic AI (NeSy)
- Explainable Grading Guidance (EGG)
- Neuron Explanations
- Ethical and Responsible Societal Systems

